"""proper trackable one_ups

Revision ID: bd60edd17185
Revises: 
Create Date: 2023-04-20 23:37:10.931285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd60edd17185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('one_up')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_up', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
